project:
  type: website
  output-dir: docs

website:
  description: "Open Science Infrastructure for Earth's Ice Sheets"
  site-url: "https://englacial.org"
  repo-url: "https://github.com/englacial/website"
  title: "englacial"
  navbar:
    right:
      - text: "team"
        menu:
        - text: Thomas Teisberg
          href: thomas.qmd
        - text: Shane Grigsby
          href: shane.qmd
      - text: "projects"
        menu:
        - text: xopr
          href: https://github.com/englacial/xopr
        - text: Living Data Products
          href: https://astera.org/call-for-proposals-living-data-products-for-ice-sheet-models/
      #  href: about.qmd
      - text: "blog"
        href: blog.qmd
      - icon: github
        href: https://github.com/englacial
      #- icon: rss
      #  href: blog.xml
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    include-in-header:
      - text: |
          <!-- Privacy-friendly analytics by Plausible -->
          <script async src="https://plausible.io/js/pa-AegmHWgLHcdedZvtA_uM7.js"></script>
          <script>
            window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
            plausible.init()
          </script>
    theme:
      - flatly #lux
      #- brand
    css: styles.css
    toc: true



