project:
  type: website
  output-dir: docs
  resources:
    - static

website:
  description: "Open Science Infrastructure for Earth's Ice Sheets"
  site-url: "https://englacial.org"
  repo-url: "https://github.com/englacial/website"
  title: "<img src='/images/logo_snowflake.png' style='max-height: 1.5em;' /> englacial"
  favicon: images/logo_snowflake.png
  navbar:
    right:
      # - text: "team"
      #   menu:
      #   - text: Thomas Teisberg
      #     href: thomas.qmd
      #   - text: Shane Grigsby
      #     href: shane.qmd
      - text: "about"
        href: about.qmd
      - text: "models"
        menu:
        - text: "AWS (new)"
          href: /static/models_aws/
        - text: "GCS (current)"
          href: /static/models_gcs/
      - text: "projects"
        menu:
        - text: "xOPR&nbsp;&nbsp;{{< fa arrow-up-right-from-square >}}"
          href: https://github.com/englacial/xopr
          target: _blank
        - text: Living Data Products
          href: pages/2025-living-data-products.qmd
      - text: "updates"
        href: updates.qmd
      - icon: github
        href: https://github.com/englacial
      #- icon: rss
      #  href: blog.xml
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    include-in-header:
      - text: |
          <!-- Privacy-friendly analytics by Plausible -->
          <script async src="https://plausible.io/js/pa-AegmHWgLHcdedZvtA_uM7.js"></script>
          <script>
            window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
            plausible.init()
          </script>
    theme:
      - flatly
      #- brand
    css: styles.css
    toc: true



